    - name:  login ocp 
      command: oc login --token={{token}}  --server={{serverurl}}
    - name:  create project 
      command: oc project  {{projectname}}
    - name:  add seesion long-term account  
      command: oc create serviceaccount nexus
    - name:  add serviceaccount acl
      command: oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:{{projectname}}:nexus
    - name:  oc create nexus3-template.yaml
      command: oc create -f roles/nexus3/templates/nexus3-template.yaml
    - name:  oc new-app
      command: oc new-app nexus3