    - name:  login ocp 
      command: oc login --token={{token}} --server={{serverurl}}
      register: result
      notify: test
    - name:  create project 
      command: oc new-project keycloak
      register: result
      notify: test
    - name:  add seesion long-term account  
      command: oc create serviceaccount keycloak
      register: result
      notify: test
    - name:  add serviceaccount acl
      command: oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:keycloak:keycloak
      register: result
      notify: test
    - name: create POSTGRESQL 
      command: oc new-app -f https://raw.githubusercontent.com/openshift/origin/master/examples/db-templates/postgresql-persistent-template.json  -p DATABASE_SERVICE_NAME={{svcName}}   -p POSTGRESQL_USER={{postgerUser}}   -p POSTGRESQL_PASSWORD={{postgerPwd}} -p POSTGRESQL_DATABASE={{database}}
    - name: create KEYCLOAK 
      command: oc new-app -f https://raw.githubusercontent.com/maslick/keycloak-docker/master/openshift-keycloak.yaml   -p KEYCLOAK_USER={{keycloakUser}}  -p KEYCLOAK_PASSWORD={{keycloakPwd}}   -p NAMESPACE=keycloak   -p HOSTNAME_HTTP={{hostname}}