




apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv3
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    kind: PersistentVolumeClaim
    namespace: tempfuuts
    name: db-mysql-data
    apiVersion: v1
  nfs:
    path: /tmp
    server: 172.17.0.2
    readOnly: false

