


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: db-mysql-data
spec:
    accessModes:
        - ReadWriteMany     
    resources:
        requests:
            storage: 2Gi      
    volumeName: nfs-pv3
