apiVersion: v1
kind: Service
metadata:
    name: mysqlsts
    labels:
       app: mysqlsts
spec:
    ports:
     - name: mysqlsts
       port: 3306
    clusterIP: None
    selector:
       app: mysqlsts
