    - name:  login ocp 
      command: oc login --token={{token}}  --server={{loginurl}}
    - name:  create project 
      command: oc  project {{projectname}}
    - name:  oc new-app
      command: oc new-app -f  roles/gogs/templates/gogs-template.yaml  --param=GOGS_VERSION=0.11.34  --param=HOSTNAME={{gogshosename}}   --param=SKIP_TLS_VERIFY=true