    token: aPUTjSB33XcS2j5_A_TUF5yalZPSrwVyqd5X-LMIGZA
    serverurl: https://api.cluster-98dc.98dc.sandbox1537.opentlc.com:6443
    catalogurl: https://raw.githubusercontent.com/OpenShiftDemos/nexus/master/nexus3-template.yaml 
    projectname: corespaceapp