- hosts: dev
  name: install keycloak
  remote_user: root
  tasks:
    - name:  login ocp 
      command: oc login --token=9IBxvlTi2-uVNpQHdbAhXyPlo9Pik0N77EvV1USi1TY --server=https://api.hzocp.sandbox801.opentlc.com:6443
      register: result
      notify: test
    - name:  create project 
      command: oc new-project activemq
      register: result
      notify: test
    - name:  remove old file 
      command: rm -rf openshift-template.yaml
      register: result
      notify: test
    - name: get  attr config
      command: wget https://raw.githubusercontent.com/natronq/openshift-activemq/master/openshift-template.yaml
    - name: create appliaction 
      command: oc process -f openshift-template.yaml | oc apply -f - 
    - name:  remove old file 
      command: rm -rf openshift-template.yaml
      register: result
      notify: test
      
  handlers:                                          
    - name: test
      command: oc delete project  activemq
      when: "result.stdout=='' " 