- hosts: dev
  name: install appNode1
  remote_user: root
  tasks:
    - name:  login ocp 
      command: oc login --token=9IBxvlTi2-uVNpQHdbAhXyPlo9Pik0N77EvV1USi1TY --server=https://api.hzocp.sandbox801.opentlc.com:6443
      register: result
      notify: test
    - name:  create project 
      command: oc new-project appNode1
      register: result  
      notify: test
    - name:  add seesion long-term account  
      command: oc create serviceaccount robot
      register: result    	  
      notify: test
    - name:  add serviceaccount acl
      command: oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:appNode1:robot
      register: result
      notify: test
    - name: del config file
      command: rm -rf springboot-s2i-isimplatform.json 	  
    - name:  get catalog config file
      command: wget https://codeSay:c43ff1fbc88f538e2d49594f01717611@gitee.com/hzopen/Template/raw/master/springboot-s2i-isimplatform.json
      register: result    
      notify: test handlers
    - name:  import catalog
      command: oc create -f springboot-s2i-isimplatform.json
      register: result     
      notify: test handlers
    - name:  source build
      command: oc new-app --template=springboot-s2i  -p APPLICATION_NAME=isimplatform  -p APPLICATION_HOSTNAME=appNode1.apps.hzocp.sandbox801.opentlc.com  -p SOURCE_REPOSITORY_URL=https://lolipopjy:f1a8e24d8ae4b3dd62aac8a67244890c@gitee.com/hzopen/agileintegration.git  -p SOURCE_REPOSITORY_REF=develop  -p MVN_PROFILE=pro  -p MEMORY_LIMIT=512Mi 
      register: result        
      notify: test handlers
    - name: del config file
      command: rm -rf springboot-s2i-isimplatform.json  
    - name:  start build
      command: oc start-build  isimplatform
      register: result      
      notify: test handlers

  handlers:                                          
    - name: test handlers
      command: oc delete project  appNode1