- hosts: dev
  name: install keycloak
  remote_user: root
  tasks:
    - name:  login ocp 
      command: oc login --token=9IBxvlTi2-uVNpQHdbAhXyPlo9Pik0N77EvV1USi1TY --server=https://api.hzocp.sandbox801.opentlc.com:6443
      register: result
      notify: test
    - name:  create project 
      command: oc new-project keycloak1
      register: result
      notify: test
    - name: create POSTGRESQL 
      command: oc new-app -f https://raw.githubusercontent.com/openshift/origin/master/examples/db-templates/postgresql-persistent-template.json  -p DATABASE_SERVICE_NAME=keycloak-db   -p POSTGRESQL_USER=keycloak   -p POSTGRESQL_PASSWORD=keycloak -p POSTGRESQL_DATABASE=keycloakdb
    - name: create KEYCLOAK_USER 
      command: oc new-app -f https://raw.githubusercontent.com/maslick/keycloak-docker/master/openshift-keycloak.yaml   -p KEYCLOAK_USER=admin  -p KEYCLOAK_PASSWORD=admin   -p NAMESPACE=keycloak1   -p HOSTNAME_HTTP=keycloak1.apps.hzocp.sandbox801.opentlc.com
    - name:  copy sql file 
      command: oc rsync 1.sql keycloak-db-1-bzzts:/var/lib/pgsql/data/userdata
    - name:  Import data
      command: psql -U keycloak -d keycloakdb -f /var/lib/pgsql/data/userdata/1.sql
      
  handlers:                                          
    - name: test
      command: oc delete project  keycloak1
      when: "result.stdout=='' " 