- hosts: dev
  name: install nexus3
  remote_user: root
  tasks:
    - name:  login ocp 
      command: oc login --token=aPUTjSB33XcS2j5_A_TUF5yalZPSrwVyqd5X-LMIGZA  --server=https://api.cluster-98dc.98dc.sandbox1537.opentlc.com:6443
      register: result
      notify: test
    - name:  create project 
      command: oc new-project nexus
      register: result
      notify: test
    - name:  add seesion long-term account  
      command: oc create serviceaccount nexus
      register: result
      notify: test
    - name:  add serviceaccount acl
      command: oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:nexus:nexus
      register: result
      notify: test
    - name: del config file
      command: rm -rf nexus3-template.yaml
    - name:  get  config file
      command: wget https://raw.githubusercontent.com/OpenShiftDemos/nexus/master/nexus3-template.yaml 
      register: result
      notify: test
    - name:  oc create nexus3-template.yaml
      command: oc create -f nexus3-template.yaml 
      register: result
      notify: test
    - name:  oc new-app
      command: oc new-app nexus3
      register: result
      notify: test
      
  handlers:                                          
    - name: test
      command: oc delete project  nexus
      when: "result.stdout=='' " 