- hosts: dev
  name: install mysql
  remote_user: root
  tasks:
    - name:  login ocp 
      command: oc login --token=VcB0GjgALr321SUrWPuzYm90tLKyOFE9NG-FpFJRtdA --server=https://api.hzocp.sandbox801.opentlc.com:6443
    - name:  get project 
      command: oc project mysql
    - name:  create phpmyadmin-template.yaml
      command:  oc create -f   ../roles/mysql56/vars/mysqlYml/phpmyadmin-template.yaml
    - name:  create mysqlsts
      command:  oc process phpmyadmin-template  | oc create -f -