    - name:  login ocp 
      command: oc login --token={{token}} --server={{serverurl}}
    - name:  create project 
      command: oc new-project activemq
    - name:  remove old file 
      command: rm -rf openshift-template.yaml
    - name: get  attr config
      command: wget {{catalogurl}}
    - name: create appliaction 
      shell: oc process -f openshift-template.yaml | oc apply -f - 
    - name:  remove old file 
      command: rm -rf openshift-template.yaml