    - name:  login ocp 
      command: oc login --token={{token}} --server={{loginurl}}
    - name:  create project 
      command: oc project {{projectname}}
    - name: create appliaction 
      shell: oc process -f roles/activeMQ/templates/openshift-template.yaml | oc apply -f - 