    - name:  login ocp 
      command: oc login --token={{token}} --server={{loginurl}}   --insecure-skip-tls-verify
    - name:  get project 
      command: oc  project {{projectname}}
    - name:  add seesion long-term account  
      command: oc create serviceaccount robotservclient
    - name:  add serviceaccount acl
      command: oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:{{projectname}}:robotservclient
    - name:  import images
      command: oc import-image chenshoumao/corepanel-s2i-is:1 --confirm --insecure
    - name:  import catalog
      command: oc create -f roles/serviceClient/templates/serviceclient-template.json 
    - name:  source build
      command: oc new-app --template=serviceclient-template -p  APPLICATION_NAME={{serviceclientappname}} -p APPLICATION_HOSTNAME={{serviceclienthosename}}  -p NAMESPACE={{namespace}}  -p SOURCE_REPOSITORY_URL={{serviceclientgiturl}}  -p SOURCE_REPOSITORY_REF={{serviceclientbranch}}  -p MVN_PROFILE={{serviceclientprofile}}   -p CURRENT_PROJECT=corespaceapp -p OPENSHIFT_URL={{loginurl}} -p OPENSHIFT_USER={{user}}  -p OPENSHIFT_PASSWORD={{password}}
    - name:  start build
      command: oc start-build  {{serviceclientappname}}