    - name:  login ocp 
      command: oc login --token={{token}} --server={{loginurl}}
    - name:  create project 
      command: oc new-project mysql
    - name:  create headlessmysql
      command:  oc create -f   roles/mysql56/vars/mysqlYml/headlessmysql.yml
    - name:  create mysqlsts
      command:  oc create -f  roles/mysql56/vars/mysqlYml/mysqlsts.yml
    - name:  create phpmyadmin-template.yaml
      command:  oc create -f   roles/mysql56/vars/phpmyadmin/phpmyadmin-template.yaml
    - name:  process phpmyadmin-template
      shell:  oc process phpmyadmin-template  | oc create -f -