    - name:  login ocp 
      command: oc login --token={{token}} --server={{loginurl}}
    - name:  create project 
      command: oc new-project mysql
    - name:  create headlessmysql
      command:  oc create -f   ../vars/mysqlYml/headlessmysql.yaml
    - name:  create mysqlsts
      command:  oc create -f  ../vars/mysqlYml/mysqlsts.yaml
    - name:  create phpmyadmin-template.yaml
      command:  oc create -f   ../vars/mysqlYml/phpmyadmin-template.yaml
    - name:  process phpmyadmin-template
      command:  oc process phpmyadmin-template  | oc create -f -