    - name: test
      command:  oc delete dc openshift-activemq && oc delete services openshift-activemq && oc delete routes activemq && oc delete imagestreams openshift-activemq
      when: "result.stdout=='' "